disabled = false
languageCode = "it"
languageName = "Italian"
weight = 1
title = "Il Turno di Guardia"

[params]
displayName = "IT"
isoCode = "it"
rtl = false
dateFormat = "2 January 2006"
description = "Il sito del Turno di Guardia"
